server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:2000/employee_management_system
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

# Uncomment the below section to use H2 in-memory database
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ""
